baseURL = "https://aitestino.github.io/blog"
languageCode = "en-us"
title = "Andrea Testino's Blog"
theme = "m10c"

[params]
  author = "Andrea Testino"
  description = "Sharing my IT adventures and CCIE DevNet journey!"
  avatar = "./static/global/avatar.JPG"
  images = ["./static/global/avatar.JPG"]

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/aitestino"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/andrea_testino"

  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/andrea-testino-891348111/"

# /config/_default/config.toml
[build]
  writeStats = true